version: '3'

services:
  inbound:
    image: nhsdev/nia-mhs-inbound:${BUILD_TAG}
    ports:
      - "443"
      - "80"
    environment:
      - TCP_PORTS=443
      - SERVICE_PORTS=443,80

  outbound:
    image: nhsdev/nia-mhs-outbound:${BUILD_TAG}
    ports:
      - "80"
    environment:
      - SERVICE_PORTS=80
      - MHS_OUTBOUND_VALIDATE_CERTIFICATE

  route:
    image: nhsdev/nia-mhs-route:${BUILD_TAG}

  rabbitmq:
    image: nhsdev/nia-rabbitmq-local:1.0.1