version: '3'

services:
  inbound:
    ports:
      - "443"
      - "80"
    environment:
      - TCP_PORTS=443
      - SERVICE_PORTS=443,80

  outbound:
    ports:
      - "80"
    environment:
      - SERVICE_PORTS=80

  inbound-lb:
    image: dockercloud/haproxy
    links:
      - inbound
    ports:
      - "443:443"
      - "8079:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - MODE=tcp
      - TIMEOUT=connect 0, client 0, server 0
  
  outbound-lb:
    image: dockercloud/haproxy
    links:
      - outbound
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - TIMEOUT=connect 0, client 0, server 0